{% set name = "PlaScope" %}
{% set version = "1.3.1" %}
{% set sha256 = "2460f4199c8f542f0e364844794e9db55cb4317d8d2effa4cac8b717a0539529" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://github.com/GuilhemRoyer/{{ name|lower }}/archive/v{{ version }}.tar.gz
  sha256: {{ sha256 }}

build:
  number: 0

requirements:
  run:
    - spades >=3.10.1
    - centrifuge ==1.0.3

about:
  home: https://github.com/GuilhemRoyer/{{ name }}
  license: GPL (>=3)
  license_family: GPL
  summary: PlaScope is a targeted approach to assess the plasmidome of bacteria.

test:
  commands:
    - plaScope.sh --version

