{% set name = "unitig-counter" %}
{% set version = "1.0.4" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://github.com/johnlees/{{ name|lower }}/archive/v{{ version }}.tar.gz
  sha256: e91e726bb9d11e25868bac990b55d9f178ae195a826992dd0be6e4508011f4a7

build:
  number: 0

requirements:
  build:
    - {{ compiler('c') }}
    - {{ compiler('cxx') }}
    - python <3
  host:
    - cmake
    - zlib
    - pthread-stubs
  run:
    - pthread-stubs

test:
  commands:
    - unitig-counter --version
    - cdbg-ops --version

about:
   home: https://github.com/johnlees/unitig-counter
   license: GNU Affero General Public License
   license_family: AGPL
   license_file: LICENSE
   summary: Uses a compressed de Bruijn graph (implemented in GATB) to count unitigs in bacterial populations.

extra:
   identifiers:
     - doi:10.1371/journal.pgen.1007758
